---
- name: Update web servers
  hosts: jenkins
  remote_user: root
  gather_facts: yes
  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.package:
        name: httpd
        state: latest
